app:
  client:
    notification-service:
      url: http://localhost:8081 # notification-service
spring:
  application:
    name: user-service

  # Database
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update

  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: secure_password
    publisher-confirm-type: correlated # Đảm bỏa message không mất phía producer
    publisher-returns:
      true # không tìm đc queue -> RabbitMQ trả message ngược về producer
      # với returns=true -> cần config callback trong code để xử lý message trả về

  # kafka
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer # String-serializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer # Java Object -> JSON
#      acks: all # đảm bảo tất cả các replica xác nhận
#      retries: 3 # tự retry khi fail
#      batch-size: 16384 # gom batch trước khi gửi // tăng hiệu suất
      # (optional) bọc thêm type info vào Header để bên kia biết class gì
#      linger-ms: 10 # chờ gom batch 10ms trước khi gửi
#      compression-type: snappy # nén message trước khi gửi //snappy/gzip/lz4
      properties:
        spring.json.add.type.headers: true
#        enable.idempotence: true # tránh duplicate message

  # cloud + openfeing
  cloud:
    openfeign:
      client:
        config:
          notification-service: # matches with @FeignClient(name=...)
            connect-timeout: 1000 # chờ connect 1s
            read-timeout: 3000 # chờ xử lý 3s

          #
          # retry
          # default: # config cho mọi service
          #  retryer: feign.Retryer.Default

          # enable feign logging
          # + cho mọi service
          # default:
          #   logger-level: FULL
          # + cho từng service
          # order-service:
          #  logger-level: HEADERS

# enable logging kiểu cũ
logging:
  level:
    feign: DEBUG
    # or log theo package
    # vduczz.userservice.infrastructure: Debug
    org.apache.kafka: DEBUG
server:
  port: 8080
