app:
  outbox:
    kafka:
      poll-interval-ms: 3000
  client:
    notification-service:
      url: http://localhost:8081 # notification-service
spring:
  application:
    name: user-service

  # Database
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update

  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: secure_password
    publisher-confirm-type: correlated # Đảm bỏa message không mất phía producer
    publisher-returns:
      true # không tìm đc queue -> RabbitMQ trả message ngược về producer
    # với returns=true -> cần config callback trong code để xử lý message trả về

  # kafka
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer # String-serializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer # Java Object -> JSON
      #      acks: all # đảm bảo tất cả các replica xác nhận
      #      retries: 3 # tự retry khi fail
      #      batch-size: 16384 # gom batch trước khi gửi // tăng hiệu suất
      #      # (optional) bọc thêm type info vào Header để bên kia biết class gì
      #      linger-ms: 10 # chờ gom batch 10ms trước khi gửi
      #      compression-type: snappy # nén message trước khi gửi //snappy/gzip/lz4
      properties:
        spring.json.add.type.headers: true
        enable.idempotence: true # tránh duplicate message

  # cloud + openfeing
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false # tắt Feign CB
      client:
        config:
          notification-service: # matches with @FeignClient(name=...)
            connect-timeout: 1000 # chờ connect 1s
            read-timeout: 3000 # chờ xử lý 3s

          #
          # retry
          # default: # config cho mọi service
          #  retryer: feign.Retryer.Default

          # enable feign logging
          # + cho mọi service
          # default:
          #   logger-level: FULL
          # + cho từng service
          # order-service:
          #  logger-level: HEADERS


# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      notification-service: # config instance có id = "notification-service"
        register-health-indicator: true # actuator
        sliding-window-size: 10 # lấy 10 request để tính failure rate
        minimum-number-of-calls: 5 # phải đủ 5 request mới bắt đầu đánh giá lỗi
        failure-rate-threshold: 50 # tỉ lệ lỗi >50% -> OPEN
        slow-call-rate-threshold: 50 # tỉ lệ request chậm >50% -> OPEN
        slow-call-duration-threshold: 3s # request >3s -> slow
        wait-duration-in-open-state: 30s # khi OPEN, tạm dừng gọi notification-service trong 30s
        permitted-number-of-calls-in-half-open-state: 3 # HALF_OPEN sử dụng 3 request để test
        automatic-transition-from-open-to-half-open-enabled: true # tự động chuyển  OPEN -> HALF_OPEN sau 30s chờ

        # exceptions
        record-exceptions: # các exception tính là lỗi -> tăng failure rate
          - java.lang.Exception
        ignore-class-binding-exceptions: # các exception được bỏ qua, không tính là lỗi
        # ...

  # retry
  retry:
    instances:
      notification-service:
        max-attempts: 3 # chạy tối đa 3 lần (tính cả lần đầu request)
        wait-duration: 2s # mỗi lần thử cách nhau 2s
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
        ignore-exceptions:
        # ...

  bulkhead: # giới hạn số request chạy đồng thời
    instances:
      notification-service:
        max-concurrent-calls: 10 # tối đa gửi 10 request đồng thời sang notification-service
        max-wait-duration: 100ms # khi queue đầy, chờ tối đa 100ms rồi reject

  timelimiter: # timeout
    instances:
      notification-service:
        timeout-duration: 5s
        cancel-running-future: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers, circuitbreakerevents, retries
  health:
    circuitbreakers:
      enabled: true

# enable logging kiểu cũ
logging:
  level:
    feign: DEBUG
    # or log theo package
    # vduczz.userservice.infrastructure: Debug
    org.apache.kafka: DEBUG
server:
  port: 8080
